esphome:
  name: esp01
  friendly_name: esp01

esp8266:
  board: esp01_1m

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "bL8VjV8VYipSHqXPzjj7eEsT2JN9XkgCfXYPVQPwQm8="

ota:
  password: "2a54585737119ba0c32fab14b5ef457a"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  domain: .lan


  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Esp01 Fallback Hotspot"
    password: "123456789"

captive_portal:
    