substitutions:
  devicename: outdoor-sensor

esphome:
  name: $devicename

esp32:
  board: lolin_s2_mini


# Enable logging
logger:

# Enable Home Assistant API
api:
  
ota:


wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  domain: .lan
  use_address: 192.168.200.143


  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "$devicename Fallback Hotspot"
    password: "123456789"

captive_portal:

text_sensor:
  - platform: wifi_info
    ip_address:
      name: ESP IP Address
    ssid:
      name: ESP Connected SSID
    bssid:
      name: ESP Connected BSSID
    mac_address:
      name: ESP Mac Wifi Address
    

mqtt:
  broker: !secret mqtt_broker
  username: !secret mqtt_username
  password: !secret mqtt_password
  birth_message:
  will_message:
  on_message:
    - topic: outdoor_sensor/ota_mode
      payload: 'ON'
      then:
        - deep_sleep.prevent: deep_sleep_1
    - topic: outdoor_sensor/sleep_mode
      payload: 'ON'
      then:
        - deep_sleep.enter: deep_sleep_1

sensor:
  - platform: dht
    pin: 18
    model: dht22
    temperature:
      name: "Outdoor Temperature"

    humidity:
      name: "Outdoor Humidity"
    update_interval: 30s

  - platform: adc
    name: "battery voltage"
    pin: 3
    update_interval: 60s
    filters:
      - multiply: 4.82435597
  - platform: template
    id: sys_esp_temperature
    name: ESP Temperature
    lambda: return temperatureRead();
    unit_of_measurement: °C
    device_class: TEMPERATURE
    update_interval: 30s
    entity_category: "diagnostic"
  - platform: uptime
    name: Uptime
    id: sys_uptime
    update_interval: 10s
  - platform: wifi_signal 
    name: RSSI
    id: wifi_signal_db
    update_interval: 1s
    entity_category: "diagnostic"
  - platform: template
    id: esp_memory
    icon: mdi:memory
    name: ESP Free Memory
    lambda: return heap_caps_get_free_size(MALLOC_CAP_INTERNAL) / 1024;
    unit_of_measurement: 'kB'
    state_class: measurement
    entity_category: "diagnostic"

    
deep_sleep:
  id: deep_sleep_1
  run_duration: 20sec # move this value to -delay- deep_sleep_evaluation script parameter
  sleep_duration: 30min

